import { MetadataRoute } from 'next';
import { getAllSlugs } from '@/lib/locations';
import { getAllAirportSlugs } from '@/lib/airports';

export default function sitemap(): MetadataRoute.Sitemap {
    const baseUrl = 'https://bahraintransportgroup.com';

    const staticPages = [
        '',
        '/about',
        '/airport-transfer',
        '/city-taxi',
        '/contact',
        '/fleet',
        '/locations',
        '/saudi-causeway',
        '/things-to-do',
        '/blog',
        '/blog/bahrain-taxi-prices',
        '/blog/uber-vs-taxi-bahrain',
        '/blog/bahrain-airport-transfers-guide',
        '/blog/top-5-best-taxi-companies-bahrain',
        '/blog/best-taxi-bahrain-2026',
        '/blog/best-bahrain-to-riyadh-taxi-2026',
        '/blog/uber-vs-careem-vs-btg-bahrain',
        '/blog/saudi-visa-king-fahad-causeway',
        '/blog/bahrain-to-riyadh-flight-vs-taxi',
        '/help-center',
        '/bahrain-to-dammam-taxi',
        '/dammam-to-bahrain-taxi',
        '/bahrain-to-khobar-taxi',
        '/manama-to-riyadh-taxi',
        '/riyadh-to-bahrain-taxi',
        '/bahrain-to-dammam-airport-taxi',
        '/dammam-airport-to-bahrain-taxi',
        '/fare-calculator',
        '/corporate-travel',
        '/student-transport',
        '/pet-transport',
        '/hotel-pickup',
        '/chauffeur-service',
        '/city-tour',
        '/wedding-transport',
        '/privacy-policy',
        '/terms-and-conditions',
        '/airports',
        '/routes/bahrain-to-dammam-taxi',
        '/routes/bahrain-to-khobar-taxi',
        '/routes/manama-to-riyadh-taxi',
        '/saudi-arabia-airports',
        '/bahrain-to-riyadh-airport-taxi',
        '/bahrain-to-qassim-airport-taxi',
        '/bahrain-to-hail-airport-taxi',
        '/bahrain-to-jeddah-airport-taxi',
        '/bahrain-to-jeddah-port-taxi',
        '/bahrain-to-medina-airport-taxi',
        '/bahrain-to-taif-airport-taxi',
        '/bahrain-to-yanbu-airport-taxi',
        '/bahrain-to-abha-airport-taxi',
        '/bahrain-to-tabuk-airport-taxi',
        '/bahrain-to-jizan-airport-taxi',
        '/bahrain-to-albaha-airport-taxi',
        '/bahrain-to-aljawf-airport-taxi',
        '/bahrain-to-alula-airport-taxi',
        '/bahrain-to-kuwait-taxi',
    ].map((route) => ({
        url: `${baseUrl}${route}/`,
        lastModified: new Date(),
        changeFrequency: 'weekly' as const,
        priority: route === '' ? 1.0 : 0.8,
    }));

    const arPages = [
        '/ar',
        '/ar/about',
        '/ar/airport-transfer',
        '/ar/city-taxi',
        '/ar/contact',
        '/ar/fleet',
        '/ar/saudi-causeway',
        '/ar/things-to-do',
        '/ar/blog',
        '/ar/blog/bahrain-taxi-prices',
        '/ar/blog/uber-vs-taxi-bahrain',
        '/ar/blog/bahrain-airport-transfers-guide',
        '/ar/blog/top-5-best-taxi-companies-bahrain',
        '/ar/blog/best-taxi-bahrain-2026',
        '/ar/blog/best-bahrain-to-riyadh-taxi-2026',
        '/ar/blog/uber-vs-careem-vs-btg-bahrain',
        '/ar/blog/saudi-visa-king-fahad-causeway',
        '/ar/blog/bahrain-to-riyadh-flight-vs-taxi',
        '/ar/help-center',
        '/ar/bahrain-to-dammam-taxi',
        '/ar/dammam-to-bahrain-taxi',
        '/ar/bahrain-to-khobar-taxi',
        '/ar/manama-to-riyadh-taxi',
        '/ar/riyadh-to-bahrain-taxi',
        '/ar/bahrain-to-dammam-airport-taxi',
        '/ar/dammam-airport-to-bahrain-taxi',
        '/ar/fare-calculator',
        '/ar/corporate-travel',
        '/ar/student-transport',
        '/ar/pet-transport',
        '/ar/hotel-pickup',
        '/ar/chauffeur-service',
        '/ar/city-tour',
        '/ar/wedding-transport',
        '/ar/privacy-policy',
        '/ar/terms-and-conditions',
    ].map((route) => ({
        url: `${baseUrl}${route}/`,
        lastModified: new Date(),
        changeFrequency: 'weekly' as const,
        priority: route === '/ar' ? 0.9 : 0.7,
    }));

    const locationPages = getAllSlugs().map((slug) => ({
        url: `${baseUrl}/locations/${slug}/`,
        lastModified: new Date(),
        changeFrequency: 'weekly' as const,
        priority: 0.9,
    }));

    const airportPages = getAllAirportSlugs().map((slug) => ({
        url: `${baseUrl}/airports/${slug}/`,
        lastModified: new Date(),
        changeFrequency: 'weekly' as const,
        priority: 0.9,
    }));

    return [...staticPages, ...arPages, ...locationPages, ...airportPages];
}
